version: "3.7"

services:
    nginx:
        build: ./nginx
        ports:
            - 80:80
        depends_on:
            - web
    web:
#        restart: always
        build:
            context: ./
            dockerfile: Dockerfile
        expose:
            -   5000
        volumes:
            - ./:/app
        env_file:
            - .env
        depends_on:
            - db
    db:
        image: postgres:alpine
        volumes:
            - postgres:/data/postgres
        ports:
            - 5432:5432
        env_file:
            - .env

volumes:
    postgres: